

spring:
  application:
    name: ap2-poc
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true




#  ai:
#    ollama:
#      base-url: http://localhost:11434
#      chat:
#        options:
#          model: llama3.2
#          max-tokens: 200
#          temperature: 0.0
#          stream: true
#          timeout: 10s

    vectorstore:
      qdrant:
        host: localhost
        port: 6334
        use-ssl: false
        collection-name: invoice-embeddings
        timeout: 30000
        max-idle-connections: 10
        initialize-schema: true
        local:
          enabled: true
          data-path: "C:/qdrant/data"
          log-level: INFO

        embedding-model: text-embedding-3-small
  datasource:
    url: jdbc:mysql://localhost:3306/ap2
    username: root
    password: "#Nilesh@12345#"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true



ghostscript:
  path: "C:/Program Files/gs/gs10.06.0/bin/gswin64c.exe"
tesseract:
  datapath: "C:/Program Files/Tesseract-OCR/tessdata"







